/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./AddressController.js";
export * from "./AdminController.js";
export * from "./AuthController.js";
export * from "./DashboardController.js";
export * from "./HomeController.js";
export * from "./IndexController.js";
export * from "./OrderController.js";
export * from "./OtherController.js";
export * from "./ProductController.js";
