/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./AddressController.js";
export * from "./AuthController.js";
export * from "./IndexController.js";
export * from "./OrderController.js";
export * from "./ProductController.js";
